import { Processo, Cliente } from '@/types/comex';

export const clientesMock: Cliente[] = [
  {
    id: 'CLI-001',
    nome: 'Empresa ABC Ltda',
    email: 'contato@empresaabc.com.br',
  },
  {
    id: 'CLI-002',
    nome: 'Comércio XYZ S.A.',
    email: 'vendas@comercioxyz.com.br',
  },
  {
    id: 'CLI-003',
    nome: 'Indústria DEF EIRELI',
    email: 'importacao@industriadef.com.br',
  },
];

export const processosMock: Processo[] = [
  {
    id: 'PROC-EXP-2026-0001',
    referencia: 'EXP-2026-0095',
    clienteId: 'CLI-001',
    tipo: 'exportacao',
    status: 'documentacao',
    dataPrevisao: '2026-02-15',
    temDocumentos: true,
    origem: 'São Paulo, BR',
    destino: 'Shanghai, CN',
    transportador: 'COSCO',
    numeroNotaFiscal: 'NF-12345',
    valor: 125000.50,
    observacoes: 'Carga de produtos eletrônicos. Aguardando documentação de exportação.',
  },
  {
    id: 'PROC-IMP-2026-0002',
    referencia: 'IMP-2026-0042',
    clienteId: 'CLI-002',
    tipo: 'importacao',
    status: 'em_transito',
    dataPrevisao: '2026-01-28',
    temDocumentos: true,
    origem: 'Rotterdam, NL',
    destino: 'Santos, BR',
    transportador: 'MSC',
    numeroNotaFiscal: 'NF-67890',
    valor: 250000.00,
    observacoes: 'Máquinas industriais. Em trânsito, previsão de chegada em 5 dias.',
  },
  {
    id: 'PROC-EXP-2026-0003',
    referencia: 'EXP-2026-0101',
    clienteId: 'CLI-003',
    tipo: 'exportacao',
    status: 'desembaraco',
    dataPrevisao: '2026-02-10',
    temDocumentos: false,
    origem: 'Rio de Janeiro, BR',
    destino: 'Los Angeles, US',
    transportador: 'Maersk',
    numeroNotaFiscal: 'NF-11111',
    valor: 87500.75,
    observacoes: 'Produtos químicos. Em processo de desembaraço alfandegário.',
  },
  {
    id: 'PROC-IMP-2026-0004',
    referencia: 'IMP-2026-0055',
    clienteId: 'CLI-001',
    tipo: 'importacao',
    status: 'liberado',
    dataPrevisao: '2026-01-20',
    temDocumentos: true,
    origem: 'Hamburg, DE',
    destino: 'São Paulo, BR',
    transportador: 'Hapag-Lloyd',
    numeroNotaFiscal: 'NF-22222',
    valor: 180000.00,
    observacoes: 'Equipamentos médicos. Processo liberado e pronto para retirada.',
  },
  {
    id: 'PROC-EXP-2026-0005',
    referencia: 'EXP-2026-0088',
    clienteId: 'CLI-002',
    tipo: 'exportacao',
    status: 'documentacao',
    dataPrevisao: '2026-02-20',
    temDocumentos: false,
    origem: 'Belo Horizonte, BR',
    destino: 'Dubai, AE',
    transportador: 'CMA CGM',
    numeroNotaFiscal: 'NF-33333',
    valor: 95000.00,
    observacoes: 'Produtos alimentícios. Aguardando documentação completa.',
  },
];
